#!/usr/bin/env python3
"""PROTOTYPE — throwaway. Version restore by copying state FORWARD.

QUESTION
    Can "restore an earlier version" be built as *copy that version's canonical
    state forward into a NEW generation* (never rewind the pointer, ADR 0039),
    such that:
      C1 the restored canonical state is byte-identical to what was recorded,
      C2 a rebuild from the restored state is byte-identical to a rebuild from
         the original version (ADR 0041's determinism claim, end to end),
      C3 later versions survive — history stays monotonic,
      C4 nothing dead-ends afterwards: commit / export / verify still work,
      C5 GC does not eat the content a version points at (ADR 0042's premise).

WHAT THIS IS
    Real engine, real document, real store. The only prototype-specific bits are
    (a) a local `versions.jsonl` written by hand, and (b) a monkeypatched
    `_gc_abandoned` that honours a keep-list — that patch is the mechanism
    ADR 0042 proposes, prototyped here to see whether it is sufficient.

NOT PRODUCTION. No tests. Nothing is deleted. Scratch workdir is created fresh
under the path given (default: <repo-parent>/proto-version-restore).

RUN
    python prototypes/version-restore-prototype.py [scratch-dir]
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import scripts.mcp_server as M  # noqa: E402
from scripts.edit import classify_edit_state, refresh_edit_projection  # noqa: E402
from scripts.review_collab import document_state, publish_current  # noqa: E402
from scripts.store import Store, store_dir_path  # noqa: E402
from scripts.typed_docx import validate_workdir  # noqa: E402

SOURCE = Path(
    r"D:/L/OB/Literature-hub/Project/专利区/20260721三个专利/支架版本链/aci_v9/s4/专利.docx"
)
# Files that ARE the version's state. Everything else (edit.md, regions.md,
# revisions.md, .review/*) is derived and regenerated by the engine.
STATE_FILES = (
    "typed.md",
    "format.json",
    "styles.json",
    "revisions.json",
    "_template.docx",
)
BOUND_FILES = ("edit.md", "edit.state.json")  # header <-> sidecar binding

KEEP: set[str] = set()  # prototype stand-in for the version-referenced GC roots


# ---------------------------------------------------------------- instrumentation
def rule(title: str) -> None:
    print(f"\n{'=' * 78}\n{title}\n{'=' * 78}")


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def code(result) -> str:
    payload = result.structuredContent if hasattr(result, "structuredContent") else result
    if isinstance(payload, str):
        payload = json.loads(payload)
    if not payload.get("isError"):
        return "ok"
    return (payload.get("diagnostics") or [{}])[0].get("code") or "error"


def state(workdir: Path, label: str) -> None:
    """Surface the full relevant state (the prototype's whole point)."""
    pointer = json.loads((workdir / "workdir.json").read_text(encoding="utf-8"))
    collab = document_state(workdir)
    typed = workdir / "typed.md"
    generations = sorted(p.name for p in (store_dir_path(workdir) / "generations").iterdir() if p.is_dir())
    print(f"  state [{label}]")
    print(f"    generation    : {pointer['generation'][:12]}")
    print(f"    typed.md      : {sha(typed)[:12]}  ({typed.stat().st_size} bytes)")
    print(f"    snapshot      : {collab['current_snapshot']['id']} {collab['current_snapshot']['typed_sha256'][:12]}"
          f"  matches_filesystem={collab['current_matches_filesystem']}")
    print(f"    generations   : {len(generations)} on disk -> {[g[:8] for g in generations]}")


def record_version(index: int, workdir: Path, label: str) -> dict:
    """The version record ADR 0040 proposes, written by hand for the prototype."""
    pointer = json.loads((workdir / "workdir.json").read_text(encoding="utf-8"))
    generation = pointer["generation"]
    manifest = json.loads(
        (store_dir_path(workdir) / "generations" / generation / "generation.json").read_text(encoding="utf-8")
    )
    collab = document_state(workdir)
    return {
        "version": f"V{index}",
        "label": label,
        "generation": generation,
        "snapshot": collab["current_snapshot"]["id"],
        "typed_sha256": collab["current_snapshot"]["typed_sha256"],
        "assets": {a["path"]: a["sha256"] for a in manifest["assets"] if a["path"] in STATE_FILES},
    }


# ---------------------------------------------------------------- the prototype
def changed_paragraphs(left: Path, right: Path) -> list[str]:
    """Paragraph ids whose text differs between two canonical states — what a
    version record wants to show as its summary."""
    from scripts.typed_core import parse_typed, visible_text

    def texts(path: Path) -> dict:
        document = parse_typed(path.read_text(encoding="utf-8"))
        return {p.paragraph_id: visible_text(p.nodes) for p in document.paragraphs}

    before, after = texts(left), texts(right)
    return sorted(pid for pid in set(before) | set(after) if before.get(pid) != after.get(pid))


def restore_core(workdir: Path, version: dict, reason: str) -> dict:
    """The proposed restore: overlay the pinned state into a NEW generation.

    Everything here runs inside the store's existing commit lane, so the
    pointer only advances and the write is journaled like any other mutation.
    """
    source_generation = store_dir_path(workdir) / "generations" / version["generation"]
    manifest = json.loads((source_generation / "generation.json").read_text(encoding="utf-8"))
    recorded = {a["path"]: a["sha256"] for a in manifest["assets"]}
    # the delta this restore introduces is measured against what is current now
    parent_generation = store_dir_path(workdir) / "generations" / json.loads(
        (workdir / "workdir.json").read_text(encoding="utf-8")
    )["generation"]

    def run(target: Path, tx=None):  # target = the NEW generation snapshot
        for name in STATE_FILES:
            origin = source_generation / name
            if not origin.is_file():
                continue
            expected = recorded.get(name)
            if expected and sha(origin) != expected:
                raise RuntimeError(f"version content corrupt: {name}")
            shutil.copyfile(origin, target / name)
        # the projection and its sidecar are bound to a canonical hash by
        # design: drop the stale pair and let the engine rebuild it from the
        # restored state, instead of copying half a binding (which the engine
        # correctly rejects as edit-header-tampered)
        for name in BOUND_FILES:
            (target / name).unlink(missing_ok=True)
        refresh_edit_projection(target, init=True)
        classify_edit_state(target)
        validate_workdir(target)
        # a restore is a canonical write: it must publish, or it strands the
        # session in collaboration drift (the dead-end class fixed in 8dd135e)
        collab = document_state(target)
        publish_current(
            target,
            expected_parent_snapshot=collab["current_snapshot"]["id"],
            origin="restore",
            changed_paragraph_ids=changed_paragraphs(parent_generation / "typed.md", target / "typed.md"),
        )
        return (
            "success",
            {"restored_from": version["version"], "reason": reason, "files": list(STATE_FILES)},
            "mutation",
            {"checks": [{"name": "history-restore", "status": "pass"}]},
            [],
        )

    result = M._mutation_tool(
        f"proto-restore-{uuid.uuid4().hex[:8]}",
        "history_restore",
        {"workdir": str(workdir), "version": version["version"]},
        workdir,
        directory=True,
        evidence_path=workdir / "run.evidence.json",
        run=run,
        store_workdir=workdir,
        require_agent_preflight=True,
    )
    payload = result.structuredContent if hasattr(result, "structuredContent") else result
    if isinstance(payload, str):
        payload = json.loads(payload)
    return {
        "result": code(result),
        "outcome": payload.get("outcome"),
        "diagnostics": [d.get("code") for d in (payload.get("diagnostics") or [])],
        "data": json.dumps(payload.get("data") or {}, ensure_ascii=False)[:200],
    }


def main() -> int:
    scratch = Path(sys.argv[1] if len(sys.argv) > 1 else REPO.parent / "proto-version-restore")
    workdir = scratch / "wd"
    if scratch.exists():
        shutil.rmtree(scratch)
    scratch.mkdir(parents=True)

    rule("0. SETUP — real document, fresh workdir")
    from scripts.extract import extract

    assert extract([str(SOURCE), "-o", str(workdir)]) == 0
    M.apply_tool_profile("editor")  # the profile agents actually get
    print("  open:", code(M.workdir_open(str(workdir), track=True)))
    versions: list[dict] = []

    rule("1. V1 — one edit, one save boundary")
    print("  patch:", code(M.document_patch(
        hunks=[{"paragraph_id": "P39", "old": "同种异体血浆", "new": "异体血浆"}],
        operation_id=f"p-{uuid.uuid4().hex[:6]}",
    )))
    print("  commit:", code(M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")))
    versions.append(record_version(1, workdir, "改第二处术语"))
    state(workdir, "after V1")

    rule("2. V2 — a second save boundary (different kind of edit: formatting)")
    result = M.format_span(
        paragraph_id="P7", old="纳米羟基磷灰石", attributes={"bold": True},
        operation_id=f"f-{uuid.uuid4().hex[:6]}",
    )
    print("  format_span:", code(result))
    print("  commit:", code(M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")))
    versions.append(record_version(2, workdir, "加粗权利要求1"))
    state(workdir, "after V2")

    rule("3. GC PROBE — does the content of V1 still exist after more mutations?")
    before = {v["version"]: (store_dir_path(workdir) / "generations" / v["generation"]).is_dir() for v in versions}
    print("  before the next mutation:", before)
    print("  patch:", code(M.document_patch(
        hunks=[{"paragraph_id": "P39", "old": "异体血浆", "new": "异体血浆层"}],
        operation_id=f"p-{uuid.uuid4().hex[:6]}",
    )))
    print("  commit:", code(M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")))
    after = {v["version"]: (store_dir_path(workdir) / "generations" / v["generation"]).is_dir() for v in versions}
    print("  after  the next mutation:", after)
    store = store_dir_path(workdir)
    referenced = set()
    pointer_now = json.loads((workdir / "workdir.json").read_text(encoding="utf-8"))
    referenced.add(pointer_now["generation"])
    journals = [d for d in (store / "transactions").iterdir() if d.is_dir()] if (store / "transactions").is_dir() else []
    for tx_dir in journals:
        for record in sorted(tx_dir.glob("*.json")):
            try:
                generation = json.loads(record.read_text(encoding="utf-8")).get("generation")
            except Exception:
                continue
            if isinstance(generation, str):
                referenced.add(generation)
    on_disk = {d.name for d in (store / "generations").iterdir() if d.is_dir()}
    reclaimable = on_disk - referenced
    version_generations = {v["generation"] for v in versions}
    at_risk = reclaimable & version_generations
    print(f"  contract: referenced={len(referenced)} on-disk={len(on_disk)} reclaimable={len(reclaimable)}")
    print(f"  versions whose content is reclaimable by contract: {len(at_risk)}/{len(versions)}"
          f" -> {[v['version'] for v in versions if v['generation'] in at_risk]}")
    print(f"  (journals keeping generations alive today: {len(journals)} tx dirs)")
    gc_eats_versions = bool(at_risk)

    rule("4. PIN MECHANISM (ADR 0042 prototyped) — keep-list honoured by GC")
    original_gc = Store._gc_abandoned

    def gc_with_keep(self, result):  # noqa: ANN001 - prototype patch
        for generation in list(KEEP):
            gen_dir = self.generations_dir / generation
            if gen_dir.is_dir():
                result.setdefault("kept", []).append(f"generation/{generation}")
        original_gc(self, result)

    Store._gc_abandoned = gc_with_keep
    KEEP.update(v["generation"] for v in versions)
    # re-pin by copying the still-missing ones back is impossible if already
    # deleted, so this run proves the mechanism on whatever survives + V3.
    print("  keep-list armed with:", [g[:8] for g in KEEP])
    print("  patch:", code(M.document_patch(
        hunks=[{"paragraph_id": "P39", "old": "异体血浆层", "new": "异体血浆"}],
        operation_id=f"p-{uuid.uuid4().hex[:6]}",
    )))
    print("  commit:", code(M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")))
    versions.append(record_version(3, workdir, "改回第二处术语"))
    KEEP.add(versions[-1]["generation"])
    print("  patch:", code(M.document_patch(
        hunks=[{"paragraph_id": "P39", "old": "异体血浆", "new": "异体血浆层"}],
        operation_id=f"p-{uuid.uuid4().hex[:6]}",
    )))
    print("  commit:", code(M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")))
    pinned = {v["version"]: (store_dir_path(workdir) / "generations" / v["generation"]).is_dir() for v in versions}
    print("  after two more mutations with the keep-list:", pinned)
    gc_safe = all(pinned.values())
    Store._gc_abandoned = original_gc
    state(workdir, "after GC probe")

    rule("5. RESTORE V1 — copy its state forward into a NEW generation")
    target = next(v for v in versions if v["version"] == "V1")
    if not (store_dir_path(workdir) / "generations" / target["generation"]).is_dir():
        print("  V1's content is gone (GC ate it) — restore must fail closed;")
        print("  re-running the restore for a surviving version instead:", versions[-1]["version"])
        target = versions[-1]
    print(f"  restoring {target['version']} ({target['label']})")
    restored = restore_core(workdir, target, reason="prototype")
    print("  mutation lane:", restored["result"])
    print("    outcome   :", restored["outcome"], "| diagnostics:", restored["diagnostics"])
    print("    data      :", restored["data"])
    state(workdir, f"after restore of {target['version']}")
    restored_snapshot = document_state(workdir)["current_snapshot"]  # the restore's own publish

    rule("6. CHECKS")
    checks: list[tuple[str, bool, str]] = []
    generation_dir = store_dir_path(workdir) / "generations" / target["generation"]

    # C1 — restored state equals what the version recorded, byte for byte
    mismatched = [name for name, digest in target["assets"].items() if sha(workdir / name) != digest]
    bound_ok = all((workdir / name).is_file() for name in BOUND_FILES)
    checks.append(("C1 restored canonical state byte-identical to the version", not mismatched,
                   f"mismatched={mismatched}; derived pair regenerated={bound_ok}"))

    # C2 — rebuild is deterministic end to end: restored workdir vs the pinned
    #      generation materialised as a plain workdir
    pinned_copy = scratch / "pinned"
    shutil.copytree(generation_dir, pinned_copy, ignore=shutil.ignore_patterns("generation.json"))
    built_a, built_b = scratch / "restored.docx", scratch / "original.docx"
    ra = M.build_docx(output=str(built_a), operation_id=f"b-{uuid.uuid4().hex[:6]}")
    M.workdir_open(str(pinned_copy))
    rb = M.build_docx(output=str(built_b), operation_id=f"b-{uuid.uuid4().hex[:6]}")
    M.workdir_open(str(workdir))
    same_bytes = built_a.exists() and built_b.exists() and sha(built_a) == sha(built_b)
    checks.append(("C2 rebuilt package identical to the original version's", same_bytes,
                   f"{sha(built_a)[:12] if built_a.exists() else '-'} vs {sha(built_b)[:12] if built_b.exists() else '-'}"))

    # C4 — no dead end: verify the export, then commit again
    verify = M.verify_output(output=str(built_a), operation_id=f"v-{uuid.uuid4().hex[:6]}")
    checks.append(("C4a verify_output passes on the restored build", code(verify) == "ok", code(verify)))
    later = M.document_patch(
        hunks=[{"paragraph_id": "P39", "old": "异体血浆", "new": "异体血浆层"}],
        operation_id=f"p-{uuid.uuid4().hex[:6]}",
    )
    commit = M.commit_sync(operation_id=f"c-{uuid.uuid4().hex[:6]}")
    checks.append(("C4b commit after a restore still works", code(later) == "ok" and code(commit) == "ok",
                   f"patch={code(later)} commit={code(commit)}"))

    # C3/C5 — monotonic history: earlier and later versions still listed + present
    survivors = {v["version"]: (store_dir_path(workdir) / "generations" / v["generation"]).is_dir() for v in versions}
    pointer = json.loads((workdir / "workdir.json").read_text(encoding="utf-8"))["generation"]
    checks.append(("C3/C5 pointer advanced, history kept", pointer != target["generation"] and survivors.get("V2", False),
                   f"pointer={pointer[:8]} survivors={survivors}"))

    # C6 — the restore published, so the collaboration ledger is consistent
    checks.append(("C6 restore publishes its own snapshot", restored_snapshot.get("origin") == "restore",
                   f"snapshot={restored_snapshot['id']} origin={restored_snapshot.get('origin')} "
                   f"changed={restored_snapshot.get('changed_paragraph_ids')}"))

    for name, ok, detail in checks:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}  — {detail}")

    rule("VERDICT")
    print(f"  C2 determinism (restored == original) : {'holds' if same_bytes else 'BROKEN'}")
    print(f"  state exact after restore             : {'holds' if not mismatched else 'BROKEN'}")
    print(f"  history monotonic, later versions kept: {'holds' if survivors.get('V2') else 'BROKEN'}")
    print(f"  no dead end after restore             : {'holds' if code(commit) == 'ok' else 'BROKEN'}")
    print(f"  GC eats version content unless pinned : {'yes (needs the keep-list)' if gc_eats_versions else 'no'}")
    print(f"\n  scratch workdir left for inspection: {workdir}")
    return 0 if all(ok for _, ok, _ in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
